### ISSUE TITLE
torch.jit.frontend.UnsupportedNodeError: break statements aren't supported

### ISSUE THREAD

**Issue by macio232** [oskopek/mvae#2]
**Describe the bug**
Running the example from README gives the following error:
```
Traceback (most recent call last):
  File "/home/maciej/.conda/envs/pt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/maciej/.conda/envs/pt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/maciej/Documents/mvae/mt/examples/run.py", line 22, in <module>
    from ..data import create_dataset
  File "/home/maciej/Documents/mvae/mt/data/__init__.py", line 18, in <module>
    from .image_reconstruction import CifarVaeDataset, MnistVaeDataset, OmniglotVaeDataset
  File "/home/maciej/Documents/mvae/mt/data/image_reconstruction.py", line 24, in <module>
    from ..mvae.distributions import EuclideanUniform
  File "/home/maciej/Documents/mvae/mt/mvae/distributions/__init__.py", line 16, in <module>
    from .hyperspherical_uniform import HypersphericalUniform
  File "/home/maciej/Documents/mvae/mt/mvae/distributions/hyperspherical_uniform.py", line 24, in <module>
    from ..ops.common import ln_2, ln_pi
  File "/home/maciej/Documents/mvae/mt/mvae/ops/__init__.py", line 18, in <module>
    from .poincare import PoincareBall
  File "/home/maciej/Documents/mvae/mt/mvae/ops/poincare.py", line 18, in <module>
    import geoopt.manifolds.poincare.math as pm
  File "/home/maciej/.local/lib/python3.7/site-packages/geoopt/__init__.py", line 1, in <module>
    from . import manifolds
  File "/home/maciej/.local/lib/python3.7/site-packages/geoopt/manifolds/__init__.py", line 6, in <module>
    from .birkhoff_polytope import BirkhoffPolytope
  File "/home/maciej/.local/lib/python3.7/site-packages/geoopt/manifolds/birkhoff_polytope.py", line 203, in <module>
    x, max_iter: int = 300, eps: float = 1e-5, tol: float = 1e-5
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/__init__.py", line 823, in script
    ast = get_jit_def(obj)
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 158, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 198, in build_def
    build_stmts(ctx, body))
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 174, in __call__
    return method(ctx, node)
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 319, in build_While
    build_stmts(ctx, stmt.body))
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 174, in __call__
    return method(ctx, node)
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 332, in build_If
    build_stmts(ctx, stmt.body),
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 122, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/maciej/.conda/envs/pt/lib/python3.7/site-packages/torch/jit/frontend.py", line 173, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: break statements aren't supported
    x, max_iter: int = 300, eps: float = 1e-5, tol: float = 1e-5
):
    iter = 0
    c = 1.0 / (x.sum(dim=-2, keepdim=True) + eps)
    r = 1.0 / ((x @ c.transpose(-1, -2)) + eps)
    while iter < max_iter:
        iter += 1
        cinv = torch.matmul(r.transpose(-1, -2), x)
        if torch.max(torch.abs(cinv * c - 1)) <= tol:
            break
            ~~~~~ <--- HERE
        c = 1.0 / (cinv + eps)
        r = 1.0 / ((x @ c.transpose(-1, -2)) + eps)
    return x * (r @ c)
```

**To Reproduce**
1. Set up your environment as described in README
2. Run ```python -m mt.examples.run --dataset="mnist" --model="h2,s2,e2" --fixed_curvature=False```

**Desktop (please complete the following information):**
 - OS: Linux (no CUDA)

**Comment by oskopek** [comment]
Hi Maciej!

Thanks for using the code. I fixed a version in the Makefile and uploaded a new version (see commit 96d851ce446d8f7e975d82ec74caabb67cfbcd77). **Please recreate your whole environment setup by first running**:
```
conda deactivate pt
conda env remove -n pt
```
and then running all the README steps again. Thanks!

Your provided example should then work just fine:
```
(pt)  $ python -m mt.examples.run --dataset="mnist" --model="h2,s2,e2" --fixed_curvature=False

CUDA is not available.
Running on: cpu
#####
VAE Model: e2,h2,s2; Epochs: 500; Time: 2020-03-16T23:28:56.472804; Fixed curvature: False; Dataset: mnist
#####
	TrainEpoch 0:	{'bce': 147.69038701468037, 'kl': 9.85506391545199, 'elbo': -157.54545093013218, 'll': 0.0, 'mi': 0.0, 'cov_norm': 0.0, 'beta': 1.0, 'comp_000_h2/curvature': -0.008264462809917356, 'comp_001_s2/curvature': 0.008264462809917356, 'comp_002_e2/curvature': 0.0}
	TrainEpoch 1:	{'bce': 122.45547009470756, 'kl': 11.968708590422095, 'elbo': -134.42417868512945, 'll': 0.0, 'mi': 0.0, 'cov_norm': 0.0, 'beta': 1.0, 'comp_000_h2/curvature': -0.01, 'comp_001_s2/curvature': 0.01, 'comp_002_e2/curvature': 0.0}
	TrainEpoch 2:	{'bce': 117.72101712977751, 'kl': 12.220480436734427, 'elbo': -129.94149756651183, 'll': 0.0, 'mi': 0.0, 'cov_norm': 0.0, 'beta': 1.0, 'comp_000_h2/curvature': -0.012345679012345678, 'comp_001_s2/curvature': 0.012345679012345678, 'comp_002_e2/curvature': 0.0}
```

Let me know if it helps or not. In case it doesn't, can you also try running `make tests` and paste the output here? Thanks!

**Comment by macio232** [comment]
Now everything works. Thank you for fast reaction!

**Comment by oskopek** [comment]
Welcome!
